//  ["tag principale", [ "tags secondaire associé (non affiché mais trouvé lors de la recherche)" ]],
var Tags = {
    "Pythagore":                ["pythagore", "triangle rectangle","egalite","pytagore"],
    "Thalès":                   ["thales", "agrandissement", "reduction", "egalite", "tales"],
    "Trigonométrie":            ["trigonometrie", "cosinus", "cos", "arccos", "sinus", "sin", "arcsin", "tangente", "tan", "arctan", "triangle rectangle"],
    "Fraction":                 ["fraction", "division", "calcul", "nombres"],
    "Fonction":                 ["fonction", "affine", "lineaire", "graphique", "courbe", "abscisse", "ordonnee", "reperage"],
    "Probabilités":             ["probabilites", "chance"],
    "Puissances":               ["puissances", "exposant"],
    "Expressions litterales":   ["expressions litterales", "x", "developpement", "factorisation", "reduction", "equation"],
    "Vrai faux":                ["vrai faux"],
    "Proportionnalité":         ["proportionnalite", "tableau", "produit en croix", "pourcentage", "echelle", "ratio"],
    "Statistique":              ["statistique", "graphique", "diagramme", "courbe", "moyenne", "mediane", "etendue", "frequence", "serie"],
    "Solide":                   ["solide", "volume", "sphere", "boule", "pyramide", "cube", "pave droit", "prisme"],
    "Géométrie":                ["geometrie", "pavage", "transformation du plan", "homothetie", "translation", "rotation", "symetrie", "cercle", "aire", "perimetre", "semblable"],
    "Scratch":                  ["scratch", "ordinateur", "algorithme", "programmation"],
    "Tableur":                  ["tableur", "ordinateur", "cellule"],
    "Arithmétique":             ["arithmetique", "nombres premiers", "premiers", "diviseur", "multiple", "decomposition", "facteurs"],
    "Tâche complexe":           ["tache complexe", "ouvert"],
    "QCM":                      ["qcm", "choix multiple"]
};


var ListExercices = [
    ["2019 - Amérique du nord",1, ["Pythagore", "Thalès", "Trigonométrie"]],
    ["2019 - Amérique du nord",2, ["Vrai faux", "Fraction", "Fonction", "Probabilités", "Expressions litterales"]],
    ["2019 - Amérique du nord",3, ["Statistique", "Tableur", "Proportionnalité"]],
    ["2019 - Amérique du nord",4, ["Scratch"]],
    ["2019 - Amérique du nord",5, ["Géométrie"]],
    ["2019 - Amérique du nord",6, ["Fonction", "Proportionnalité"]],
    ["2019 - Amérique du nord",7, ["Solide"]],
    ["2019 - Amérique du nord",8, ["Statistique"]],
    ["2019 - Amérique du sud",1,  ["Vrai faux", "Statistique", "Arithmétique", "Géométrie", "Agrandissement"]],
    ["2019 - Amérique du sud",2,  ["Tableur", "Proportionnalité"]],
    ["2019 - Amérique du sud",3,  ["Expressions litterales", "Equation"]],
    ["2019 - Amérique du sud",4,  ["Pythagore", "Thalès", "Trigonométrie", "Volume"]],
    ["2019 - Amérique du sud",5,  ["Tâche complexe"]],
    ["2019 - Amérique du sud",6,  ["Scratch"]],
    ["2019 - Antilles-Guyane Juin",1, ["Arithmétique", "Probabilités"]],
    ["2019 - Antilles-Guyane Juin",2, ["Scratch"]],
    ["2019 - Antilles-Guyane Juin",3, ["Proportionnalité", "Statistique", "Tableur"]],
    ["2019 - Antilles-Guyane Juin",4, ["Thalès", "Trigonométrie"]],
    ["2019 - Antilles-Guyane Juin",5, ["Expressions litterales", "Vrai faux"]],
    ["2019 - Antilles-Guyane Juin",6, ["Proportionnalité", "Fonction", "Solide"]],
    ["2019 - Antilles-Guyane Septembre",1, ["Thalès", "Pythagore", "Proportionnalité"]],
    ["2019 - Antilles-Guyane Septembre",2, ["Arithmétique"]],
    ["2019 - Antilles-Guyane Septembre",3, ["Fonction", "Tâche complexe"]],
    ["2019 - Antilles-Guyane Septembre",4, ["Proportionnalité", "Solide"]],
    ["2019 - Antilles-Guyane Septembre",5, ["Expressions litterales", "Tableur"]],
    ["2019 - Antilles-Guyane Septembre",6, ["Scratch", "Probabilités"]],
    ["2019 - Asie",1, ["Expressions litterales"]],
    ["2019 - Asie",2, ["Proportionnalité"]],
    ["2019 - Asie",3, ["Scratch"]],
    ["2019 - Asie",4, ["Tâche complexe", "Solide"]],
    ["2019 - Asie",5, ["Géométrie", "Pythagore"]],
    ["2019 - Asie",6, ["Proportionnalité", "Tâche complexe"]],
    ["2019 - Asie",7, ["Fonction", "Tableur"]],
    ["2019 - Centres étrangers",1, ["QCM", "Arithmétique", "Proportionnalité", "Trigonométrie", "Statistique", "Géométrie"]],
    ["2019 - Centres étrangers",2, ["Expressions litterales", "Tableur"]],
    ["2019 - Centres étrangers",3, ["Scratch", "Géométrie", "Expressions litterales"]],
    ["2019 - Centres étrangers",4, ["Probabilité"]],
    ["2019 - Centres étrangers",5, ["Thalès"]],
    ["2019 - Centres étrangers",6, ["Proportionnalité", "Fonction"]],
    ["2019 - Centres étrangers",7, ["Tâche complexe", "Solide"]],
    ["2019 - Grèce",1, ["Probabilité"]],
    ["2019 - Grèce",2, ["Trigonométrie", "Géométrie"]],
    ["2019 - Grèce",3, ["Proportionnalité", "Géométrie", "Arithmétique"]],
    ["2019 - Grèce",4, ["Scratch"]],
    ["2019 - Grèce",5, ["Expressions litterales", "Fonction", "QCM"]],
    ["2019 - Grèce",6, ["Géométrie", "Solide", "Tâche complexe"]],
    ["2019 - Métropole",1, ["Arithmétique"]],
    ["2019 - Métropole",2, ["Trigonométrie", "Géométrie"]],
    ["2019 - Métropole",3, ["Tâche complexe", "Solide", "Statistique"]],
    ["2019 - Métropole",4, ["Scratch", "Probabilité"]],
    ["2019 - Métropole",5, ["Géométrie", "Proportionnalité"]],
    ["2019 - Métropole",6, ["Expressions litterales"]],
    ["2019 - Nouvelle-Calédonie",1, ["QCM", "Géométrie", "Expressions litterales", "Puissances"]],
    ["2019 - Nouvelle-Calédonie",2, ["Probabilité"]],
    ["2019 - Nouvelle-Calédonie",3, ["Géométrie"]],
    ["2019 - Nouvelle-Calédonie",4, ["Pythagore", "Thalès"]],
    ["2019 - Nouvelle-Calédonie",5, ["Fonction"]],
    ["2019 - Nouvelle-Calédonie",6, ["Fonction", "Expressions litterales"]],
    ["2019 - Nouvelle-Calédonie",7, ["Solide", "Tâche complexe"]],
    ["2019 - Nouvelle-Calédonie",8, ["Scratch"]],
    ["2019 - Polynésie",1, ["QCM", "Arithmétique", "Thalès"]],
    ["2019 - Polynésie",2, ["Scratch", "Fonction"]],
    ["2019 - Polynésie",3, ["Probabilité"]],
    ["2019 - Polynésie",4, ["Solide"]],
    ["2019 - Polynésie",5, ["Pythagore", "Trigonométrie"]],
    ["2019 - Polynésie",6, ["Statistique"]],
    ["2019 - Polynésie",7, ["Fonction", "Tâche complexe"]],
]

/* Load data */